# Generated by Django 4.0.4 on 2022-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Име')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Ел.Поща')),
                ('phone_number', models.IntegerField()),
                ('addres', models.TextField()),
                ('country', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=14)),
            ],
        ),
    ]
