# Generated by Django 4.0.4 on 2022-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Име')),
                ('telephone', models.IntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('type_of_tape', models.CharField(choices=[('Текстилна лента без покритие', 'Текстилна лента без покритие'), ('Текстилна лента с PVC покритие', 'Текстилна лента с PVC покритие'), ('Текстилна лента с PU покритие', 'Текстилна лента с PU покритие'), ('Текстилна лента с TPO покритие', 'Текстилна лента с TPO покритие'), ('Текстилна лента с гумено покритие', 'Текстилна лента с гумено покритие')], max_length=33, verbose_name='Вид лента')),
                ('connection_method', models.CharField(choices=[('Отворена', 'Отворена'), ('Залепена', 'Залепена'), ('Метална връзка', 'Метална връзка')], max_length=14, verbose_name='Начин на свързване')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Ширина')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Дължина')),
                ('blade_height', models.FloatField(blank=True, null=True, verbose_name='Височина на лопатките')),
                ('blade_length', models.FloatField(blank=True, null=True, verbose_name='Дължина на лопатките')),
                ('step_between_blades', models.FloatField(blank=True, null=True, verbose_name='Стъпка между лопатките')),
                ('height_of_side_stops', models.FloatField(blank=True, null=True, verbose_name='Височина на странични ограничители')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Относно')),
            ],
        ),
    ]
