# Generated by Django 4.0.4 on 2022-10-15 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conveyor_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('diameter', models.FloatField(blank=True, null=True)),
                ('D_3', models.FloatField(blank=True, null=True, verbose_name='D3')),
                ('E', models.FloatField(blank=True, null=True)),
                ('B', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='Град')),
                ('state', models.CharField(max_length=200, null=True, verbose_name='Област')),
                ('zipcode', models.CharField(max_length=200, null=True, verbose_name='Пощенски код')),
                ('date_added', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conveyor_app.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conveyor_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conveyor_app.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conveyor_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='AskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Име')),
                ('telephone', models.IntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('type_of_tape', models.CharField(choices=[('Текстилна лента без покритие', 'Текстилна лента без покритие'), ('Текстилна лента с PVC покритие', 'Текстилна лента с PVC покритие'), ('Текстилна лента с PU покритие', 'Текстилна лента с PU покритие'), ('Текстилна лента с TPO покритие', 'Текстилна лента с TPO покритие'), ('Текстилна лента с гумено покритие', 'Текстилна лента с гумено покритие')], max_length=33, verbose_name='Вид лента')),
                ('connection_method', models.CharField(choices=[('Отворена', 'Отворена'), ('Залепена', 'Залепена'), ('Метална връзка', 'Метална връзка')], max_length=14, verbose_name='Начин на свързване')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Ширина')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Дължина')),
                ('blade_height', models.FloatField(blank=True, null=True, verbose_name='Височина на лопатките')),
                ('blade_length', models.FloatField(blank=True, null=True, verbose_name='Дължина на лопатките')),
                ('step_between_blades', models.FloatField(blank=True, null=True, verbose_name='Стъпка между лопатките')),
                ('height_of_side_stops', models.FloatField(blank=True, null=True, verbose_name='Височина на странични ограничители')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Относно')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
