# Generated by Django 4.0.4 on 2022-08-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conveyor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpurchases',
            old_name='purchase',
            new_name='UCF_ids',
        ),
    ]
