# Generated by Django 4.0.4 on 2022-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='O_D',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='W',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
