# Generated by Django 4.0.4 on 2022-08-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyor_app', '0002_rename_purchase_userpurchases_ucf_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchases',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
