# Generated by Django 4.0.4 on 2022-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyor_app', '0002_askmodel_blade_height_askmodel_blade_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askmodel',
            name='blade_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Височина на лопатките'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='blade_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Дължина на лопатките'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='connection_method',
            field=models.CharField(choices=[], max_length=14, verbose_name='Начин на свързване'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='height_of_side_stops',
            field=models.FloatField(blank=True, null=True, verbose_name='Височина на странични ограничители'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Дължина'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='step_between_blades',
            field=models.FloatField(blank=True, null=True, verbose_name='Стъпка между лопатките'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='type_of_tape',
            field=models.CharField(choices=[], max_length=33, verbose_name='Вид лента'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
