# Generated by Django 4.0.4 on 2022-09-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyor_app', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='Град'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='Област'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='zipcode',
            field=models.CharField(max_length=200, null=True, verbose_name='Пощенски код'),
        ),
    ]
