# Generated by Django 4.0.4 on 2022-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyor_app', '0003_alter_askmodel_blade_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askmodel',
            name='connection_method',
            field=models.CharField(choices=[('Отворена', 'Отворена'), ('Залепена', 'Залепена'), ('Метална връзка', 'Метална връзка')], max_length=14, verbose_name='Начин на свързване'),
        ),
        migrations.AlterField(
            model_name='askmodel',
            name='type_of_tape',
            field=models.CharField(choices=[('Текстилна лента без покритие', 'Текстилна лента без покритие'), ('Текстилна лента с PVC покритие', 'Текстилна лента с PVC покритие'), ('Текстилна лента с PU покритие', 'Текстилна лента с PU покритие'), ('Текстилна лента с TPO покритие', 'Текстилна лента с TPO покритие'), ('Текстилна лента с гумено покритие', 'Текстилна лента с гумено покритие')], max_length=33, verbose_name='Вид лента'),
        ),
    ]
