# Generated by Django 4.0.4 on 2022-08-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyor_app', '0004_remove_userpurchases_quantity_ucflbodies_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucflbodies',
            name='quantity',
        ),
        migrations.AddField(
            model_name='userpurchases',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
